/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeeshopapp;

import java.util.Calendar;
import java.util.GregorianCalendar;

import sun.invoke.empty.Empty;

/**
 *
 * @author Nishna2
 */
public class Cook_Subpanel extends javax.swing.JPanel {

    /**
     * Creates new form Cook_Subpanel
     */
    public Cook_Subpanel(String name) {
        initComponents();
        
        jLabel_cookname.setText("Cook_" + name);
        this.setVisible(true);
        this.setName(name);
        this.repaint();
        this.revalidate();
        this.setName(name);
        
        //System.out.println("In Cook Subpanel "+  +this.getComponentCount()+ this.getName());
        //-------------------------------------------------------------------------------------
        display_cooking_status();
        //-------------------------------------------------------------------------------------
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_cookname = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_cookname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_cookname.setText("Cook <1>");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_cookname)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_cookname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void display_cooking_status() {
        //Function that updates date and time
        Thread thread_datetime = new Thread(){
            public void run(){
                for(;;){
                    String new_data = Serve.serveQueue.toString() ;

                    String old_data = jTextArea1.getText();
                    jTextArea1.setText(new_data + "\n" + old_data);
                    try{
                        sleep(2000);
                    }
                    catch(InterruptedException ex){
                        System.out.println(ex.getStackTrace());
                    }
                }
            }
        };
        thread_datetime.start();
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_cookname;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
