/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeeshopapp;

/**
 *
 * @author Nishna2
 */
public class Cook_Subpanel extends javax.swing.JPanel {

    /**
     * Creates new form Cook_Subpanel
     */
    public Cook_Subpanel(String name) {
        initComponents();
        
        jLabel_cookname.setText("Cook_" + name);
        this.setVisible(true);
        this.setName(name);
        this.repaint();
        this.revalidate();
        this.setName(name);
        
        System.out.println("In Cook Subpanel "+  +this.getComponentCount()+ this.getName());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_cookname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_cooking_status = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_cookname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_cookname.setText("Cook <1>");

        jList_cooking_status.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList_cooking_status);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_cookname)
                .addGap(0, 344, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_cookname)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_cookname;
    private javax.swing.JList<String> jList_cooking_status;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
