/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.util.*;

import model.*;
import controller.*;

/**
 *
 * @author Nishna2
 */
public class Cook_Subpanel extends javax.swing.JPanel
						   implements Runnable{

    /**
     * Creates new form Cook_Subpanel
     * 
     */
	String text = null;
	String name;
    public Cook_Subpanel(String name) {
        initComponents();
        
        jLabel_cookname.setText(name);
        this.setVisible(true);
        this.name = name;
        this.repaint();
        this.revalidate();
        Thread t=new Thread(this,this.name);
        t.start();
        
        //System.out.println("In Cook Subpanel "+  +this.getComponentCount()+ this.getName());
        //-------------------------------------------------------------------------------------
        //display_cooking_status_old();
        //-------------------------------------------------------------------------------------
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_cookname = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_cookname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_cookname.setText("Cook <1>");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_cookname)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_cookname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_cookname;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
    public void run() {
        while(true){
        	String text="No order to process";
        	LinkedList<Order> cOrder=ProcessClass.cookList.get(this.name).getCurr();
        	if(!cOrder.isEmpty())
        	{
        		
        		text="\n Preparation time :"+ProcessClass.cookList.get(this.name).getMilliSec();
        		text+="\nCurrently Preparing:"+cOrder.getFirst().getCustId();
        	for(Order o:cOrder){
        		
        		
        		String itemId=o.getItemId();
        		String itemName=ProcessClass.itemlist.get(itemId).getItemName();
        		text+="\n" + itemName + " " + o.getQuantity();
        	}
        	text+="\n"+ProcessClass.cookList.get(this.name).getSec();
        	try{Thread.sleep(1000);}catch(Exception e) {}
        	}
            jTextArea1.setText(text);    
        	
        }
    }




	
}
