/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.*;
import java.util.*;
import controller.*;

public class Waiter_Subpanel extends javax.swing.JPanel implements Runnable {

	String name;
    /**
     * Creates new form Waiter_Subpanel
     */
    public Waiter_Subpanel(String name) {
        initComponents();
        /*
        // Layout the content vertically
        BoxLayout layout = new BoxLayout(this, BoxLayout.Y_AXIS);
        this.setLayout(layout);*/
        this.name=name;
        jLabel_waitername.setText(name);
        //System.out.println("In WaiterSubpanel "+  +this.getComponentCount()+ jLabel_waitername.getText());
        this.setVisible(true);
        this.repaint();
        this.revalidate();
        Thread t=new Thread(this,this.name);
        t.start();
    }
    
    public void run() {
        //Function that updates date and time
    	 while(true)
    	  {
    	         String text="";
    	         LinkedList<Order> cOrder=ProcessClass.waiterList.get(this.name).getCurr();
    	         if(!cOrder.isEmpty())
    	         {
    	         text="Currently Servicing:"+cOrder.getFirst().getCustId();
    	         for(Order o:cOrder){
    	          String itemId=o.getItemId();
    	          String itemName=ProcessClass.itemlist.get(itemId).getItemName();
    	          text+="\n" + itemName + " " + o.getQuantity();
    	         }
    	         }
    	         //try{Thread.sleep(1000);}catch(Exception e) {}
    	            jTextArea1.setText(text);     
    	        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_waitername = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_waitername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_waitername.setText("Waiter <1>");
        
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_waitername)
                .addGap(0, 244, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_waitername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_waitername;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
