/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeeshopapp;

import java.awt.Component;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.BoxLayout;

/**
 *
 * @author Nishna2
 */
public class Waiter_Subpanel extends javax.swing.JPanel {

    /**
     * Creates new form Waiter_Subpanel
     */
    public Waiter_Subpanel(String name) {
        initComponents();
        /*
        // Layout the content vertically
        BoxLayout layout = new BoxLayout(this, BoxLayout.Y_AXIS);
        this.setLayout(layout);*/
        jLabel_waitername.setText("Waiter_" + name);
        System.out.println("In WaiterSubpanel "+  +this.getComponentCount()+ jLabel_waitername.getText());
        this.setVisible(true);
        DateTime();
        this.repaint();
        this.revalidate();
        this.setName(name);
    }
    
    public void DateTime() {
        //Function that updates date and time
        Thread thread_datetime = new Thread(){
            public void run(){
                for(;;){
                    Calendar calendar = new GregorianCalendar();
                    int mm = calendar.get(Calendar.MONTH);
                    int yy = calendar.get(Calendar.YEAR);
                    int dd = calendar.get(Calendar.DAY_OF_MONTH);
                    int ss = calendar.get(Calendar.SECOND);
                    int min = calendar.get(Calendar.MINUTE);
                    int hh = calendar.get(Calendar.HOUR);
                    /*jTextArea1.append("Date :  " + dd + "/ " + (mm + 1) + "/ " + yy +
                            "    " + hh + ":" + min + ":" + ss + "\n");
                    */
                    String new_data = "Date :  " + dd + "/ " + (mm + 1) + "/ " + yy +
                            "    " + hh + ":" + min + ":" + ss + "\n" ;
                    String old_data = jTextArea1.getText();
                    jTextArea1.setText(new_data + "\n" + old_data);
                    try{
                        sleep(2000);
                    }
                    catch(InterruptedException ex){
                        System.out.println(ex.getStackTrace());
                    }
                }
            }
        };
        thread_datetime.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_waitername = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_waitername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_waitername.setText("Waiter <1>");
        
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_waitername)
                .addGap(0, 244, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_waitername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_waitername;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
